# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
	s.name = 'valid-array'
	s.version = File.read('VERSION').chomp
	s.specification_version = 1
	s.date = '2013-08-28'
	
	s.homepage = 'http://github.com/kevincox/valid-array'
	s.authors = ['Kevin Cox', 'Ryan Biesemeyer']
	s.email = 'kevincox@kevincox.ca'
	s.summary = 'Provides methods for creating type-enforced Arrays'
	s.description = <<-'EOS'
		All methods that alter the contents of an array that implements this
		Gem are first checked to ensure that the added items are of the types
		allowed. All methods behave exactly as their Array counterparts,
		including additional forms, block processing, etc.
	EOS
	s.licenses = ['MIT']
	
	s.files = Dir['lib/**/*.rb', 'spec/**/*.rb']
	s.extra_rdoc_files = [
		'LICENSE',
		'README.rdoc'
	]
	s.require_paths = ['lib']
	s.add_development_dependency('rdoc', ['~> 3.9'])
	
	s.rubygems_version = '2.0.3'
end

